# fly.toml app configuration file generated for telegram-imdb-rating-bot-0cxbfg on 2024-11-28T08:19:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegram-imdb-rating-bot-0cxbfg'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
